development:
  adapter: postgresql
  database: cliq_development
  username: postgres
  password:
  encoding: utf8
  pool: 5

test: &test
  adapter: postgresql
  database: cliq_test
  username: postgres
  password:
  encoding: utf8
  pool: 5

cucumber:
  <<: *test

production:
  adapter: postgresql
  encoding: unicode
  database: cliq_production
  pool: 5
